### ISSUE TITLE
Add shell script to start the application

### ISSUE THREAD

**Issue by glen** [rocky02/q_it#9]
Create a `bin/run` file which kicks of the execution.
Users can do something like this
`./bin/run publish hello_test 5` or
`./bin/run subscribe https://sqs.us-east-1.amazonaws.com/3491033029360/hello_test 7`

**Comment by rocky02** [comment]
Implemented and done in [PR](https://github.com/rocky02/q_it/pull/14)

**Comment by glen** [comment]
Completed in PR #14
